controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_index:
    path: /
    controller: App\Controller\MovieController::index
    methods: [GET]

api_login_check:
    path: /api/login_check

api_login:
    path: /api/login
    controller: App\Controller\SecurityController::login
    methods: [POST]

api_logout:
    path: /api/logout
    controller: App\Controller\SecurityController::logout
    methods: [POST]

api_register:
    path: /api/register
    controller: App\Controller\SecurityController::register
    methods: [POST]
